-- 1. Tạo các bảng không phụ thuộc (Parent Tables)
CREATE TABLE cinema (
                        cinema_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name varchar(255),
                        address varchar(255),
                        city varchar(255),
                        district varchar(255)
);

CREATE TABLE movie (
                       movie_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       title varchar(255),
                       director varchar(255),
                       genre varchar(255),
                       duration integer,
                       limit_age integer,
                       poster varchar(255),
                       trailer_url varchar(255),
                       description varchar(255),
                       day_start date,
                       day_end date
);

CREATE TABLE day_type (
                          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          day_type varchar(255) UNIQUE NOT NULL, -- Dùng để liên kết với ticket_price
                          day_start date,
                          day_end date
);

CREATE TABLE employee (
                          employee_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          first_name varchar(255),
                          last_name varchar(255),
                          email varchar(255) UNIQUE,
                          phone varchar(255) UNIQUE,
                          position varchar(255) NOT NULL,
                          CONSTRAINT employee_position_check CHECK (position IN ('EMPLOYEE', 'MANAGER', 'ADMIN'))
);

CREATE TABLE permission (
                            permission_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name varchar(255) UNIQUE NOT NULL,
                            description varchar(255)
);

CREATE TABLE role (
                      role_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name varchar(255) UNIQUE NOT NULL,
                      description varchar(255)
);

CREATE TABLE invalidated_token (
                                   id varchar(255) PRIMARY KEY,
                                   expiry_time timestamp(6)
);

-- 2. Tạo các bảng Account (Sử dụng UUID - varchar(255))
CREATE TABLE member (
                        member_id varchar(255) PRIMARY KEY,
                        username varchar(255) UNIQUE NOT NULL,
                        password varchar(255) NOT NULL,
                        email varchar(255) UNIQUE NOT NULL,
                        phone_number varchar(255) UNIQUE NOT NULL,
                        first_name varchar(255),
                        last_name varchar(255),
                        dob date,
                        day_created timestamp(6) NOT NULL,
                        status varchar(255) NOT NULL,
                        CONSTRAINT member_status_check CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE employee_account (
                                  employee_account_id varchar(255) PRIMARY KEY,
                                  username varchar(255) UNIQUE NOT NULL,
                                  password varchar(255) NOT NULL,
                                  email varchar(255) UNIQUE,
                                  employee_id bigint UNIQUE NOT NULL,
                                  day_created timestamp(6) NOT NULL,
                                  status varchar(255) NOT NULL,
                                  CONSTRAINT employee_account_status_check CHECK (status IN ('ACTIVE', 'INACTIVE')),
                                  CONSTRAINT fk_employee FOREIGN KEY (employee_id) REFERENCES employee(employee_id)
);

-- 3. Tạo các bảng quan hệ trung gian (Roles & Permissions)
CREATE TABLE role_permissions (
                                  role_role_id bigint NOT NULL,
                                  permissions_permission_id bigint NOT NULL,
                                  PRIMARY KEY (role_role_id, permissions_permission_id),
                                  CONSTRAINT fk_role_permissions_role FOREIGN KEY (role_role_id) REFERENCES role(role_id),
                                  CONSTRAINT fk_role_permissions_perm FOREIGN KEY (permissions_permission_id) REFERENCES permission(permission_id)
);

CREATE TABLE member_roles (
                              member_member_id varchar(255) NOT NULL,
                              roles_role_id bigint NOT NULL,
                              PRIMARY KEY (member_member_id, roles_role_id),
                              CONSTRAINT fk_member_roles_member FOREIGN KEY (member_member_id) REFERENCES member(member_id),
                              CONSTRAINT fk_member_roles_role FOREIGN KEY (roles_role_id) REFERENCES role(role_id)
);

CREATE TABLE employee_account_roles (
                                        employee_account_employee_account_id varchar(255) NOT NULL,
                                        roles_role_id bigint NOT NULL,
                                        PRIMARY KEY (employee_account_employee_account_id, roles_role_id),
                                        CONSTRAINT fk_emp_roles_acc FOREIGN KEY (employee_account_employee_account_id) REFERENCES employee_account(employee_account_id),
                                        CONSTRAINT fk_emp_roles_role FOREIGN KEY (roles_role_id) REFERENCES role(role_id)
);

-- 4. Tạo các bảng nghiệp vụ rạp (Room, Seat, Showtime)
CREATE TABLE room (
                      room_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      room_name varchar(255),
                      cinema_id bigint NOT NULL,
                      CONSTRAINT fk_room_cinema FOREIGN KEY (cinema_id) REFERENCES cinema(cinema_id)
);

CREATE TABLE seat (
                      seat_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      seat_number integer NOT NULL,
                      seat_row char(1),
                      seat_type varchar(255),
                      room_id bigint NOT NULL,
                      CONSTRAINT seat_seat_type_check CHECK (seat_type IN ('CLASSIC', 'VIP')),
                      CONSTRAINT fk_seat_room FOREIGN KEY (room_id) REFERENCES room(room_id)
);

CREATE TABLE show_time (
                           showtime_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           start_time timestamp(6),
                           movie_id bigint NOT NULL,
                           room_id bigint NOT NULL,
                           CONSTRAINT uk_showtime UNIQUE (start_time, room_id),
                           CONSTRAINT fk_showtime_movie FOREIGN KEY (movie_id) REFERENCES movie(movie_id),
                           CONSTRAINT fk_showtime_room FOREIGN KEY (room_id) REFERENCES room(room_id)
);

-- 5. Giá vé và Giao dịch (TicketPrice, Booking)
CREATE TABLE ticket_price (
                              id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              price double precision NOT NULL,
                              seat_type varchar(255),
                              cinema_id bigint NOT NULL,
                              day_type varchar(255) NOT NULL, -- Liên kết theo String như yêu cầu [cite: 48, 180]
                              CONSTRAINT ticket_price_seat_type_check CHECK (seat_type IN ('CLASSIC', 'VIP')),
                              CONSTRAINT fk_price_cinema FOREIGN KEY (cinema_id) REFERENCES cinema(cinema_id),
                              CONSTRAINT fk_price_daytype FOREIGN KEY (day_type) REFERENCES day_type(day_type)
);

CREATE TABLE booking (
                         booking_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         total_price double precision NOT NULL,
                         create_time timestamp(6),
                         booking_status varchar(255),
                         member_id varchar(255) NOT NULL,
                         CONSTRAINT booking_booking_status_check CHECK (booking_status IN ('PENDING', 'CONFIRM')),
                         CONSTRAINT fk_booking_member FOREIGN KEY (member_id) REFERENCES member(member_id)
);

CREATE TABLE booking_detail (
                                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                price double precision NOT NULL,
                                seat_status varchar(255),
                                booking_id bigint NOT NULL,
                                seat_id bigint NOT NULL,
                                showtime_id bigint NOT NULL,
                                CONSTRAINT booking_detail_seat_status_check CHECK (seat_status IN ('BOOKED', 'AVAILABLE', 'HELD')),
                                CONSTRAINT uk_seat_showtime UNIQUE (seat_id, showtime_id),
                                CONSTRAINT fk_detail_booking FOREIGN KEY (booking_id) REFERENCES booking(booking_id),
                                CONSTRAINT fk_detail_seat FOREIGN KEY (seat_id) REFERENCES seat(seat_id),
                                CONSTRAINT fk_detail_showtime FOREIGN KEY (showtime_id) REFERENCES show_time(showtime_id)
);

CREATE TABLE paymenturl (
                            url varchar(2048) PRIMARY KEY,
                            amount double precision NOT NULL,
                            created_at timestamp(6) NOT NULL,
                            booking_id bigint UNIQUE NOT NULL,
                            member_id varchar(255) NOT NULL,
                            CONSTRAINT fk_pay_booking FOREIGN KEY (booking_id) REFERENCES booking(booking_id),
                            CONSTRAINT fk_pay_member FOREIGN KEY (member_id) REFERENCES member(member_id)
);

INSERT INTO role (name, description) VALUES ('ADMIN', 'All Permission');